sudo: required
services:
  - docker

before_install:
  - docker build -t luccasmmg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true luccasmmg/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "DockerReact"
  bucket_name: "elasticbeanstalk-sa-east-1-821626484152"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
